### ISSUE TITLE
Update to MC 1.8.8

### ISSUE THREAD

**Issue by jwalt** [alalwww/SpawnChecker#23]
Hi, 

Attached is a patch that updates SpawnChecker for Minecraft+Forge 1.8.8. There have been some changes to the rendering code in MC, but it wasn't too difficult to update SpawnChecker.

Note: You need an updated gradle JAR, e.g. from the latest Forge 1.8.8

Note2: build.gradle uses a newer MCP snapshot than Forge recommends, because in the recommended snapshot, the rendering code has not been deobfuscated sufficiently.

[1.8.8.diff.txt](https://github.com/alalwww/SpawnChecker/files/70210/1.8.8.diff.txt)

**Comment by alalwww** [comment]
https://www.dropbox.com/s/1l5x63sqlrsbb0z/SpawnChecker-2.3-SNAPSHOT.jar?dl=0
Thanks!

殆どテストしていません。
Minecraftが起動するかの確認のみ行いました。
1.8.8 forge reccomended がリリースされた後に再度テストします。
