### ISSUE TITLE
1.17以降について

### ISSUE THREAD

**Issue by peco2282** [alalwww/SpawnChecker#33]
@alalwww さんが1.16.4まで開発されたのをフォークして以降のものを公開しても良いでしょうか。

**Comment by alalwww** [comment]
@peco2282 
コードについてはライセンスの通りです。ただしアイコンなどの画像は自作ではないものも含まれているため、別途ライセンスを明記などしていないためお願いレベルになりますが、できれば再利用は避けて貰いたいです。

なお、スポーン条件の判定などはMinecraft本体のコードを参考にしたり真似たりしている部分が大半な為、意図的にコピーレフトなライセンスとしており、取り回しづらいと思います。
また、私のローカル環境に特化した状態かつ現在公開している部分のコードやその他色々なものが半端な状態で止まってしまっているため、そのまま再利用するのはおそらく困難ではないかと思います。
そのため、スポーン判定機能を持つオリジナルのModを新規作成するなどしたほうが、おそらく取り回しやすいのではないかと思います。…が判断はおまかせします。

**Comment by peco2282** [comment]
素早い返信ありがとうございます。

自分はまだModdingを始めて短いのでREしながらLGPLライセンスに沿って参考にさせていただきます。
フォークしたものはアーカイブにした方がよろしいですか？

**Comment by alalwww** [comment]
> フォークしたものはアーカイブにした方がよろしいですか？

フォークしたリポジトリ自体はこちらの持ち物ではないので、おまかせします。

**Comment by peco2282** [comment]
了解しました。返信ありがとうございました。
